[build]
  functions = "functions"  # Location of your serverless functions
  publish = "public"       # Location of your static files (like HTML, CSS, JS)

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/chat"
  status = 200
