[build]
  command = "npm install"
  functions = "functions"  # Directory where serverless functions are stored
  publish = "public"       # Directory for static files (e.g., HTML, CSS, JS)

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"  # Redirect all traffic to your serverless function
  status = 200